version: "3.9"

services:

  backend:
    build: ./production-backend
    ports:
      - "8080:8080"
    container_name: production-backend

  frontend:
    build: ./production-frontend
    ports:
      - "5173:5173"
    container_name: production-frontend
    depends_on:
      - backend